# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: scotts-cheap-bot

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x
  environment: 
    SLACK_URL: "https://hooks.slack.com/services/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"

# The `functions` block defines what code to deploy
functions:
  newCheapFlight:
    handler: handler.newCheapFlight
